trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: ubuntu-18.04

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore

- task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    arguments: '--configuration $(BuildConfiguration)'

- task: Docker@2
  inputs:
    containerRegistry: 'blood-bowl-league'
    repository: 'modmoto/led-backendwall'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest