trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'

- task: Docker@2
  inputs:
    containerRegistry: 'official-docker-modmoto'
    repository: 'modmoto/led-wall'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '.'
    tags: |
      $(System.PullRequest.PullRequestNumber)
      latest