trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'blood-bowl-league'
    repository: 'modmoto/led-wall'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest