version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 4001:27017
  led-wall:
    build: .
    restart: always
    ports:
      - 4000:80
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo